typography_spectrum: 0.3673835
color:
  saturation: 0.7656728
  lightness: 0.9739447
  brandStrength: 0.02295553
  brandColors:
    - '#0C1210'
    - '#5A87CB'
    - '#3E3B32'
    - '#E9F1FE'
    - '#B6C7BF'
  rhythmicContrast: 0.3716017
layout_spectrum: 0.02508961
name: 'Erakor Lagoon Holiday House '
title: YOUR PRIVATE GETAWAY IN PARADISE
description: A beautiful beachfront holiday home on stunning Er
