typography_spectrum: 0.3673835
color:
  saturation: 0.7656728
  lightness: 0.9739447
  brandStrength: 0.02295553
  brandColors:
    - '#0C1210'
    - '#5A87CB'
    - '#3E3B32'
    - '#E9F1FE'
    - '#B6C7BF'
  rhythmicContrast: 0.3716017
layout_spectrum: 0.02508961
author:
  name: Brenton Luchow
  email: brentonluchow@me.com
  url: erakorlagoonhouse.holiday
name: 'Erakor Lagoon Holiday House '
navigation:
  - name: Port Vila
    id: a53ac62e-1714-475b-a1b6-af3e7d454fa6
    type: content
  - name: The House
    id: d9b03673-9f27-4871-91c0-1c362b0e9079
    type: content
title: YOUR PRIVATE GETAWAY IN PARADISE
description: A beachfront holiday home on stunning Erakor Lagoon
